apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/mvam75/test-foo-argo-foo.git
    targetRevision: master
    path: bootstrap/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
