apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: echo
spec:
  project: default
  source:
    repoURL: https://github.com/mvam75/test-foo-argo-foo.git
    targetRevision: master
    path: apps/thirdparty/echo/environments/local
    plugin:
      env:
        - name: TARGET_FILE
          value: main.jsonnet
  destination:
    server: https://kubernetes.default.svc
    namespace: echo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
