{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='clusterClass', url='', help='"ClusterClass is a template which can be used to create managed topologies."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of ClusterClass', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'cluster.x-k8s.io/v1beta1',
    kind: 'ClusterClass',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"ClusterClassSpec describes the desired state of the ClusterClass."'),
  spec: {
    '#controlPlane':: d.obj(help='"ControlPlane is a reference to a local struct that holds the details for provisioning the Control Plane for the Cluster."'),
    controlPlane: {
      '#machineHealthCheck':: d.obj(help='"MachineHealthCheck defines a MachineHealthCheck for this ControlPlaneClass. This field is supported if and only if the ControlPlane provider template referenced above is Machine based and supports setting replicas."'),
      machineHealthCheck: {
        '#remediationTemplate':: d.obj(help='"RemediationTemplate is a reference to a remediation template provided by an infrastructure provider. \\n This field is completely optional, when filled, the MachineHealthCheck controller creates a new object from the template referenced and hands off remediation of the machine to a controller that lives outside of Cluster API."'),
        remediationTemplate: {
          '#withApiVersion':: d.fn(help='"API version of the referent."', args=[d.arg(name='apiVersion', type=d.T.string)]),
          withApiVersion(apiVersion): { spec+: { controlPlane+: { machineHealthCheck+: { remediationTemplate+: { apiVersion: apiVersion } } } } },
          '#withFieldPath':: d.fn(help='"If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: \\"spec.containers{name}\\" (where \\"name\\" refers to the name of the container that triggered the event) or if no container name is specified \\"spec.containers[2]\\" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object. TODO: this design is not final and this field is subject to change in the future."', args=[d.arg(name='fieldPath', type=d.T.string)]),
          withFieldPath(fieldPath): { spec+: { controlPlane+: { machineHealthCheck+: { remediationTemplate+: { fieldPath: fieldPath } } } } },
          '#withKind':: d.fn(help='"Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"', args=[d.arg(name='kind', type=d.T.string)]),
          withKind(kind): { spec+: { controlPlane+: { machineHealthCheck+: { remediationTemplate+: { kind: kind } } } } },
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { controlPlane+: { machineHealthCheck+: { remediationTemplate+: { name: name } } } } },
          '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { spec+: { controlPlane+: { machineHealthCheck+: { remediationTemplate+: { namespace: namespace } } } } },
          '#withResourceVersion':: d.fn(help='"Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
          withResourceVersion(resourceVersion): { spec+: { controlPlane+: { machineHealthCheck+: { remediationTemplate+: { resourceVersion: resourceVersion } } } } },
          '#withUid':: d.fn(help='"UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"', args=[d.arg(name='uid', type=d.T.string)]),
          withUid(uid): { spec+: { controlPlane+: { machineHealthCheck+: { remediationTemplate+: { uid: uid } } } } },
        },
        '#unhealthyConditions':: d.obj(help='"UnhealthyConditions contains a list of the conditions that determine whether a node is considered unhealthy. The conditions are combined in a logical OR, i.e. if any of the conditions is met, the node is unhealthy."'),
        unhealthyConditions: {
          '#withTimeout':: d.fn(help='', args=[d.arg(name='timeout', type=d.T.string)]),
          withTimeout(timeout): { timeout: timeout },
          '#withType':: d.fn(help='', args=[d.arg(name='type', type=d.T.string)]),
          withType(type): { type: type },
        },
        '#withMaxUnhealthy':: d.fn(help='"Any further remediation is only allowed if at most \\"MaxUnhealthy\\" machines selected by \\"selector\\" are not healthy."', args=[d.arg(name='maxUnhealthy', type=d.T.any)]),
        withMaxUnhealthy(maxUnhealthy): { spec+: { controlPlane+: { machineHealthCheck+: { maxUnhealthy: maxUnhealthy } } } },
        '#withNodeStartupTimeout':: d.fn(help='"Machines older than this duration without a node will be considered to have failed and will be remediated. If you wish to disable this feature, set the value explicitly to 0."', args=[d.arg(name='nodeStartupTimeout', type=d.T.string)]),
        withNodeStartupTimeout(nodeStartupTimeout): { spec+: { controlPlane+: { machineHealthCheck+: { nodeStartupTimeout: nodeStartupTimeout } } } },
        '#withUnhealthyConditions':: d.fn(help='"UnhealthyConditions contains a list of the conditions that determine whether a node is considered unhealthy. The conditions are combined in a logical OR, i.e. if any of the conditions is met, the node is unhealthy."', args=[d.arg(name='unhealthyConditions', type=d.T.array)]),
        withUnhealthyConditions(unhealthyConditions): { spec+: { controlPlane+: { machineHealthCheck+: { unhealthyConditions: if std.isArray(v=unhealthyConditions) then unhealthyConditions else [unhealthyConditions] } } } },
        '#withUnhealthyConditionsMixin':: d.fn(help='"UnhealthyConditions contains a list of the conditions that determine whether a node is considered unhealthy. The conditions are combined in a logical OR, i.e. if any of the conditions is met, the node is unhealthy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='unhealthyConditions', type=d.T.array)]),
        withUnhealthyConditionsMixin(unhealthyConditions): { spec+: { controlPlane+: { machineHealthCheck+: { unhealthyConditions+: if std.isArray(v=unhealthyConditions) then unhealthyConditions else [unhealthyConditions] } } } },
        '#withUnhealthyRange':: d.fn(help='"Any further remediation is only allowed if the number of machines selected by \\"selector\\" as not healthy is within the range of \\"UnhealthyRange\\". Takes precedence over MaxUnhealthy. Eg. \\"[3-5]\\" - This means that remediation will be allowed only when: (a) there are at least 3 unhealthy machines (and) (b) there are at most 5 unhealthy machines"', args=[d.arg(name='unhealthyRange', type=d.T.string)]),
        withUnhealthyRange(unhealthyRange): { spec+: { controlPlane+: { machineHealthCheck+: { unhealthyRange: unhealthyRange } } } },
      },
      '#machineInfrastructure':: d.obj(help='"MachineInfrastructure defines the metadata and infrastructure information for control plane machines. \\n This field is supported if and only if the control plane provider template referenced above is Machine based and supports setting replicas."'),
      machineInfrastructure: {
        '#ref':: d.obj(help='"Ref is a required reference to a custom resource offered by a provider."'),
        ref: {
          '#withApiVersion':: d.fn(help='"API version of the referent."', args=[d.arg(name='apiVersion', type=d.T.string)]),
          withApiVersion(apiVersion): { spec+: { controlPlane+: { machineInfrastructure+: { ref+: { apiVersion: apiVersion } } } } },
          '#withFieldPath':: d.fn(help='"If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: \\"spec.containers{name}\\" (where \\"name\\" refers to the name of the container that triggered the event) or if no container name is specified \\"spec.containers[2]\\" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object. TODO: this design is not final and this field is subject to change in the future."', args=[d.arg(name='fieldPath', type=d.T.string)]),
          withFieldPath(fieldPath): { spec+: { controlPlane+: { machineInfrastructure+: { ref+: { fieldPath: fieldPath } } } } },
          '#withKind':: d.fn(help='"Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"', args=[d.arg(name='kind', type=d.T.string)]),
          withKind(kind): { spec+: { controlPlane+: { machineInfrastructure+: { ref+: { kind: kind } } } } },
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { controlPlane+: { machineInfrastructure+: { ref+: { name: name } } } } },
          '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { spec+: { controlPlane+: { machineInfrastructure+: { ref+: { namespace: namespace } } } } },
          '#withResourceVersion':: d.fn(help='"Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
          withResourceVersion(resourceVersion): { spec+: { controlPlane+: { machineInfrastructure+: { ref+: { resourceVersion: resourceVersion } } } } },
          '#withUid':: d.fn(help='"UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"', args=[d.arg(name='uid', type=d.T.string)]),
          withUid(uid): { spec+: { controlPlane+: { machineInfrastructure+: { ref+: { uid: uid } } } } },
        },
      },
      '#metadata':: d.obj(help='"Metadata is the metadata applied to the machines of the ControlPlane. At runtime this metadata is merged with the corresponding metadata from the topology. \\n This field is supported if and only if the control plane provider template referenced is Machine based."'),
      metadata: {
        '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotations(annotations): { spec+: { controlPlane+: { metadata+: { annotations: annotations } } } },
        '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
        withAnnotationsMixin(annotations): { spec+: { controlPlane+: { metadata+: { annotations+: annotations } } } },
        '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { spec+: { controlPlane+: { metadata+: { labels: labels } } } },
        '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { spec+: { controlPlane+: { metadata+: { labels+: labels } } } },
      },
      '#ref':: d.obj(help='"Ref is a required reference to a custom resource offered by a provider."'),
      ref: {
        '#withApiVersion':: d.fn(help='"API version of the referent."', args=[d.arg(name='apiVersion', type=d.T.string)]),
        withApiVersion(apiVersion): { spec+: { controlPlane+: { ref+: { apiVersion: apiVersion } } } },
        '#withFieldPath':: d.fn(help='"If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: \\"spec.containers{name}\\" (where \\"name\\" refers to the name of the container that triggered the event) or if no container name is specified \\"spec.containers[2]\\" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object. TODO: this design is not final and this field is subject to change in the future."', args=[d.arg(name='fieldPath', type=d.T.string)]),
        withFieldPath(fieldPath): { spec+: { controlPlane+: { ref+: { fieldPath: fieldPath } } } },
        '#withKind':: d.fn(help='"Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"', args=[d.arg(name='kind', type=d.T.string)]),
        withKind(kind): { spec+: { controlPlane+: { ref+: { kind: kind } } } },
        '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { controlPlane+: { ref+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { controlPlane+: { ref+: { namespace: namespace } } } },
        '#withResourceVersion':: d.fn(help='"Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
        withResourceVersion(resourceVersion): { spec+: { controlPlane+: { ref+: { resourceVersion: resourceVersion } } } },
        '#withUid':: d.fn(help='"UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"', args=[d.arg(name='uid', type=d.T.string)]),
        withUid(uid): { spec+: { controlPlane+: { ref+: { uid: uid } } } },
      },
    },
    '#infrastructure':: d.obj(help='"Infrastructure is a reference to a provider-specific template that holds the details for provisioning infrastructure specific cluster for the underlying provider. The underlying provider is responsible for the implementation of the template to an infrastructure cluster."'),
    infrastructure: {
      '#ref':: d.obj(help='"Ref is a required reference to a custom resource offered by a provider."'),
      ref: {
        '#withApiVersion':: d.fn(help='"API version of the referent."', args=[d.arg(name='apiVersion', type=d.T.string)]),
        withApiVersion(apiVersion): { spec+: { infrastructure+: { ref+: { apiVersion: apiVersion } } } },
        '#withFieldPath':: d.fn(help='"If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: \\"spec.containers{name}\\" (where \\"name\\" refers to the name of the container that triggered the event) or if no container name is specified \\"spec.containers[2]\\" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object. TODO: this design is not final and this field is subject to change in the future."', args=[d.arg(name='fieldPath', type=d.T.string)]),
        withFieldPath(fieldPath): { spec+: { infrastructure+: { ref+: { fieldPath: fieldPath } } } },
        '#withKind':: d.fn(help='"Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"', args=[d.arg(name='kind', type=d.T.string)]),
        withKind(kind): { spec+: { infrastructure+: { ref+: { kind: kind } } } },
        '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { infrastructure+: { ref+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { infrastructure+: { ref+: { namespace: namespace } } } },
        '#withResourceVersion':: d.fn(help='"Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
        withResourceVersion(resourceVersion): { spec+: { infrastructure+: { ref+: { resourceVersion: resourceVersion } } } },
        '#withUid':: d.fn(help='"UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"', args=[d.arg(name='uid', type=d.T.string)]),
        withUid(uid): { spec+: { infrastructure+: { ref+: { uid: uid } } } },
      },
    },
    '#patches':: d.obj(help='"Patches defines the patches which are applied to customize referenced templates of a ClusterClass. Note: Patches will be applied in the order of the array."'),
    patches: {
      '#definitions':: d.obj(help='"Definitions define inline patches. Note: Patches will be applied in the order of the array. Note: Exactly one of Definitions or External must be set."'),
      definitions: {
        '#jsonPatches':: d.obj(help='"JSONPatches defines the patches which should be applied on the templates matching the selector. Note: Patches will be applied in the order of the array."'),
        jsonPatches: {
          '#valueFrom':: d.obj(help='"ValueFrom defines the value of the patch. Note: Either Value or ValueFrom is required for add and replace operations. Only one of them is allowed to be set at the same time."'),
          valueFrom: {
            '#withTemplate':: d.fn(help='"Template is the Go template to be used to calculate the value. A template can reference variables defined in .spec.variables and builtin variables. Note: The template must evaluate to a valid YAML or JSON value."', args=[d.arg(name='template', type=d.T.string)]),
            withTemplate(template): { valueFrom+: { template: template } },
            '#withVariable':: d.fn(help='"Variable is the variable to be used as value. Variable can be one of the variables defined in .spec.variables or a builtin variable."', args=[d.arg(name='variable', type=d.T.string)]),
            withVariable(variable): { valueFrom+: { variable: variable } },
          },
          '#withOp':: d.fn(help='"Op defines the operation of the patch. Note: Only `add`, `replace` and `remove` are supported."', args=[d.arg(name='op', type=d.T.string)]),
          withOp(op): { op: op },
          '#withPath':: d.fn(help='"Path defines the path of the patch. Note: Only the spec of a template can be patched, thus the path has to start with /spec/. Note: For now the only allowed array modifications are `append` and `prepend`, i.e.: * for op: `add`: only index 0 (prepend) and - (append) are allowed * for op: `replace` or `remove`: no indexes are allowed"', args=[d.arg(name='path', type=d.T.string)]),
          withPath(path): { path: path },
          '#withValue':: d.fn(help='"Value defines the value of the patch. Note: Either Value or ValueFrom is required for add and replace operations. Only one of them is allowed to be set at the same time. Note: We have to use apiextensionsv1.JSON instead of our JSON type, because controller-tools has a hard-coded schema for apiextensionsv1.JSON which cannot be produced by another type (unset type field). Ref: https://github.com/kubernetes-sigs/controller-tools/blob/d0e03a142d0ecdd5491593e941ee1d6b5d91dba6/pkg/crd/known_types.go#L106-L111"', args=[d.arg(name='value', type=d.T.any)]),
          withValue(value): { value: value },
        },
        '#selector':: d.obj(help='"Selector defines on which templates the patch should be applied."'),
        selector: {
          '#matchResources':: d.obj(help='"MatchResources selects templates based on where they are referenced."'),
          matchResources: {
            '#machineDeploymentClass':: d.obj(help='"MachineDeploymentClass selects templates referenced in specific MachineDeploymentClasses in .spec.workers.machineDeployments."'),
            machineDeploymentClass: {
              '#withNames':: d.fn(help='"Names selects templates by class names."', args=[d.arg(name='names', type=d.T.array)]),
              withNames(names): { selector+: { matchResources+: { machineDeploymentClass+: { names: if std.isArray(v=names) then names else [names] } } } },
              '#withNamesMixin':: d.fn(help='"Names selects templates by class names."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='names', type=d.T.array)]),
              withNamesMixin(names): { selector+: { matchResources+: { machineDeploymentClass+: { names+: if std.isArray(v=names) then names else [names] } } } },
            },
            '#withControlPlane':: d.fn(help='"ControlPlane selects templates referenced in .spec.ControlPlane. Note: this will match the controlPlane and also the controlPlane machineInfrastructure (depending on the kind and apiVersion)."', args=[d.arg(name='controlPlane', type=d.T.boolean)]),
            withControlPlane(controlPlane): { selector+: { matchResources+: { controlPlane: controlPlane } } },
            '#withInfrastructureCluster':: d.fn(help='"InfrastructureCluster selects templates referenced in .spec.infrastructure."', args=[d.arg(name='infrastructureCluster', type=d.T.boolean)]),
            withInfrastructureCluster(infrastructureCluster): { selector+: { matchResources+: { infrastructureCluster: infrastructureCluster } } },
          },
          '#withApiVersion':: d.fn(help='"APIVersion filters templates by apiVersion."', args=[d.arg(name='apiVersion', type=d.T.string)]),
          withApiVersion(apiVersion): { selector+: { apiVersion: apiVersion } },
          '#withKind':: d.fn(help='"Kind filters templates by kind."', args=[d.arg(name='kind', type=d.T.string)]),
          withKind(kind): { selector+: { kind: kind } },
        },
        '#withJsonPatches':: d.fn(help='"JSONPatches defines the patches which should be applied on the templates matching the selector. Note: Patches will be applied in the order of the array."', args=[d.arg(name='jsonPatches', type=d.T.array)]),
        withJsonPatches(jsonPatches): { jsonPatches: if std.isArray(v=jsonPatches) then jsonPatches else [jsonPatches] },
        '#withJsonPatchesMixin':: d.fn(help='"JSONPatches defines the patches which should be applied on the templates matching the selector. Note: Patches will be applied in the order of the array."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='jsonPatches', type=d.T.array)]),
        withJsonPatchesMixin(jsonPatches): { jsonPatches+: if std.isArray(v=jsonPatches) then jsonPatches else [jsonPatches] },
      },
      '#external':: d.obj(help='"External defines an external patch. Note: Exactly one of Definitions or External must be set."'),
      external: {
        '#withGenerateExtension':: d.fn(help='"GenerateExtension references an extension which is called to generate patches."', args=[d.arg(name='generateExtension', type=d.T.string)]),
        withGenerateExtension(generateExtension): { external+: { generateExtension: generateExtension } },
        '#withValidateExtension':: d.fn(help='"ValidateExtension references an extension which is called to validate the topology."', args=[d.arg(name='validateExtension', type=d.T.string)]),
        withValidateExtension(validateExtension): { external+: { validateExtension: validateExtension } },
      },
      '#withDefinitions':: d.fn(help='"Definitions define inline patches. Note: Patches will be applied in the order of the array. Note: Exactly one of Definitions or External must be set."', args=[d.arg(name='definitions', type=d.T.array)]),
      withDefinitions(definitions): { definitions: if std.isArray(v=definitions) then definitions else [definitions] },
      '#withDefinitionsMixin':: d.fn(help='"Definitions define inline patches. Note: Patches will be applied in the order of the array. Note: Exactly one of Definitions or External must be set."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='definitions', type=d.T.array)]),
      withDefinitionsMixin(definitions): { definitions+: if std.isArray(v=definitions) then definitions else [definitions] },
      '#withDescription':: d.fn(help='"Description is a human-readable description of this patch."', args=[d.arg(name='description', type=d.T.string)]),
      withDescription(description): { description: description },
      '#withEnabledIf':: d.fn(help='"EnabledIf is a Go template to be used to calculate if a patch should be enabled. It can reference variables defined in .spec.variables and builtin variables. The patch will be enabled if the template evaluates to `true`, otherwise it will be disabled. If EnabledIf is not set, the patch will be enabled per default."', args=[d.arg(name='enabledIf', type=d.T.string)]),
      withEnabledIf(enabledIf): { enabledIf: enabledIf },
      '#withName':: d.fn(help='"Name of the patch."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
    },
    '#variables':: d.obj(help='"Variables defines the variables which can be configured in the Cluster topology and are then used in patches."'),
    variables: {
      '#schema':: d.obj(help='"Schema defines the schema of the variable."'),
      schema: {
        '#openAPIV3Schema':: d.obj(help='"OpenAPIV3Schema defines the schema of a variable via OpenAPI v3 schema. The schema is a subset of the schema used in Kubernetes CRDs."'),
        openAPIV3Schema: {
          '#withAdditionalProperties':: d.fn(help='"AdditionalProperties specifies the schema of values in a map (keys are always strings). NOTE: Can only be set if type is object. NOTE: AdditionalProperties is mutually exclusive with Properties. NOTE: This field uses PreserveUnknownFields and Schemaless, because recursive validation is not possible."', args=[d.arg(name='additionalProperties', type=d.T.any)]),
          withAdditionalProperties(additionalProperties): { schema+: { openAPIV3Schema+: { additionalProperties: additionalProperties } } },
          '#withDefault':: d.fn(help='"Default is the default value of the variable. NOTE: Can be set for all types."', args=[d.arg(name='default', type=d.T.any)]),
          withDefault(default): { schema+: { openAPIV3Schema+: { default: default } } },
          '#withDescription':: d.fn(help='"Description is a human-readable description of this variable."', args=[d.arg(name='description', type=d.T.string)]),
          withDescription(description): { schema+: { openAPIV3Schema+: { description: description } } },
          '#withEnum':: d.fn(help='"Enum is the list of valid values of the variable. NOTE: Can be set for all types."', args=[d.arg(name='enum', type=d.T.array)]),
          withEnum(enum): { schema+: { openAPIV3Schema+: { enum: if std.isArray(v=enum) then enum else [enum] } } },
          '#withEnumMixin':: d.fn(help='"Enum is the list of valid values of the variable. NOTE: Can be set for all types."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='enum', type=d.T.array)]),
          withEnumMixin(enum): { schema+: { openAPIV3Schema+: { enum+: if std.isArray(v=enum) then enum else [enum] } } },
          '#withExample':: d.fn(help='"Example is an example for this variable."', args=[d.arg(name='example', type=d.T.any)]),
          withExample(example): { schema+: { openAPIV3Schema+: { example: example } } },
          '#withExclusiveMaximum':: d.fn(help='"ExclusiveMaximum specifies if the Maximum is exclusive. NOTE: Can only be set if type is integer or number."', args=[d.arg(name='exclusiveMaximum', type=d.T.boolean)]),
          withExclusiveMaximum(exclusiveMaximum): { schema+: { openAPIV3Schema+: { exclusiveMaximum: exclusiveMaximum } } },
          '#withExclusiveMinimum':: d.fn(help='"ExclusiveMinimum specifies if the Minimum is exclusive. NOTE: Can only be set if type is integer or number."', args=[d.arg(name='exclusiveMinimum', type=d.T.boolean)]),
          withExclusiveMinimum(exclusiveMinimum): { schema+: { openAPIV3Schema+: { exclusiveMinimum: exclusiveMinimum } } },
          '#withFormat':: d.fn(help="\"Format is an OpenAPI v3 format string. Unknown formats are ignored. For a list of supported formats please see: (of the k8s.io/apiextensions-apiserver version we're currently using) https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apiserver/validation/formats.go NOTE: Can only be set if type is string.\"", args=[d.arg(name='format', type=d.T.string)]),
          withFormat(format): { schema+: { openAPIV3Schema+: { format: format } } },
          '#withItems':: d.fn(help='"Items specifies fields of an array. NOTE: Can only be set if type is array. NOTE: This field uses PreserveUnknownFields and Schemaless, because recursive validation is not possible."', args=[d.arg(name='items', type=d.T.any)]),
          withItems(items): { schema+: { openAPIV3Schema+: { items: items } } },
          '#withMaxItems':: d.fn(help='"MaxItems is the max length of an array variable. NOTE: Can only be set if type is array."', args=[d.arg(name='maxItems', type=d.T.integer)]),
          withMaxItems(maxItems): { schema+: { openAPIV3Schema+: { maxItems: maxItems } } },
          '#withMaxLength':: d.fn(help='"MaxLength is the max length of a string variable. NOTE: Can only be set if type is string."', args=[d.arg(name='maxLength', type=d.T.integer)]),
          withMaxLength(maxLength): { schema+: { openAPIV3Schema+: { maxLength: maxLength } } },
          '#withMaximum':: d.fn(help='"Maximum is the maximum of an integer or number variable. If ExclusiveMaximum is false, the variable is valid if it is lower than, or equal to, the value of Maximum. If ExclusiveMaximum is true, the variable is valid if it is strictly lower than the value of Maximum. NOTE: Can only be set if type is integer or number."', args=[d.arg(name='maximum', type=d.T.integer)]),
          withMaximum(maximum): { schema+: { openAPIV3Schema+: { maximum: maximum } } },
          '#withMinItems':: d.fn(help='"MinItems is the min length of an array variable. NOTE: Can only be set if type is array."', args=[d.arg(name='minItems', type=d.T.integer)]),
          withMinItems(minItems): { schema+: { openAPIV3Schema+: { minItems: minItems } } },
          '#withMinLength':: d.fn(help='"MinLength is the min length of a string variable. NOTE: Can only be set if type is string."', args=[d.arg(name='minLength', type=d.T.integer)]),
          withMinLength(minLength): { schema+: { openAPIV3Schema+: { minLength: minLength } } },
          '#withMinimum':: d.fn(help='"Minimum is the minimum of an integer or number variable. If ExclusiveMinimum is false, the variable is valid if it is greater than, or equal to, the value of Minimum. If ExclusiveMinimum is true, the variable is valid if it is strictly greater than the value of Minimum. NOTE: Can only be set if type is integer or number."', args=[d.arg(name='minimum', type=d.T.integer)]),
          withMinimum(minimum): { schema+: { openAPIV3Schema+: { minimum: minimum } } },
          '#withPattern':: d.fn(help='"Pattern is the regex which a string variable must match. NOTE: Can only be set if type is string."', args=[d.arg(name='pattern', type=d.T.string)]),
          withPattern(pattern): { schema+: { openAPIV3Schema+: { pattern: pattern } } },
          '#withProperties':: d.fn(help='"Properties specifies fields of an object. NOTE: Can only be set if type is object. NOTE: Properties is mutually exclusive with AdditionalProperties. NOTE: This field uses PreserveUnknownFields and Schemaless, because recursive validation is not possible."', args=[d.arg(name='properties', type=d.T.any)]),
          withProperties(properties): { schema+: { openAPIV3Schema+: { properties: properties } } },
          '#withRequired':: d.fn(help='"Required specifies which fields of an object are required. NOTE: Can only be set if type is object."', args=[d.arg(name='required', type=d.T.array)]),
          withRequired(required): { schema+: { openAPIV3Schema+: { required: if std.isArray(v=required) then required else [required] } } },
          '#withRequiredMixin':: d.fn(help='"Required specifies which fields of an object are required. NOTE: Can only be set if type is object."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='required', type=d.T.array)]),
          withRequiredMixin(required): { schema+: { openAPIV3Schema+: { required+: if std.isArray(v=required) then required else [required] } } },
          '#withType':: d.fn(help='"Type is the type of the variable. Valid values are: object, array, string, integer, number or boolean."', args=[d.arg(name='type', type=d.T.string)]),
          withType(type): { schema+: { openAPIV3Schema+: { type: type } } },
          '#withUniqueItems':: d.fn(help='"UniqueItems specifies if items in an array must be unique. NOTE: Can only be set if type is array."', args=[d.arg(name='uniqueItems', type=d.T.boolean)]),
          withUniqueItems(uniqueItems): { schema+: { openAPIV3Schema+: { uniqueItems: uniqueItems } } },
        },
      },
      '#withName':: d.fn(help='"Name of the variable."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withRequired':: d.fn(help='"Required specifies if the variable is required. Note: this applies to the variable as a whole and thus the top-level object defined in the schema. If nested fields are required, this will be specified inside the schema."', args=[d.arg(name='required', type=d.T.boolean)]),
      withRequired(required): { required: required },
    },
    '#withPatches':: d.fn(help='"Patches defines the patches which are applied to customize referenced templates of a ClusterClass. Note: Patches will be applied in the order of the array."', args=[d.arg(name='patches', type=d.T.array)]),
    withPatches(patches): { spec+: { patches: if std.isArray(v=patches) then patches else [patches] } },
    '#withPatchesMixin':: d.fn(help='"Patches defines the patches which are applied to customize referenced templates of a ClusterClass. Note: Patches will be applied in the order of the array."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='patches', type=d.T.array)]),
    withPatchesMixin(patches): { spec+: { patches+: if std.isArray(v=patches) then patches else [patches] } },
    '#withVariables':: d.fn(help='"Variables defines the variables which can be configured in the Cluster topology and are then used in patches."', args=[d.arg(name='variables', type=d.T.array)]),
    withVariables(variables): { spec+: { variables: if std.isArray(v=variables) then variables else [variables] } },
    '#withVariablesMixin':: d.fn(help='"Variables defines the variables which can be configured in the Cluster topology and are then used in patches."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='variables', type=d.T.array)]),
    withVariablesMixin(variables): { spec+: { variables+: if std.isArray(v=variables) then variables else [variables] } },
    '#workers':: d.obj(help='"Workers describes the worker nodes for the cluster. It is a collection of node types which can be used to create the worker nodes of the cluster."'),
    workers: {
      '#machineDeployments':: d.obj(help='"MachineDeployments is a list of machine deployment classes that can be used to create a set of worker nodes."'),
      machineDeployments: {
        '#machineHealthCheck':: d.obj(help='"MachineHealthCheck defines a MachineHealthCheck for this MachineDeploymentClass."'),
        machineHealthCheck: {
          '#remediationTemplate':: d.obj(help='"RemediationTemplate is a reference to a remediation template provided by an infrastructure provider. \\n This field is completely optional, when filled, the MachineHealthCheck controller creates a new object from the template referenced and hands off remediation of the machine to a controller that lives outside of Cluster API."'),
          remediationTemplate: {
            '#withApiVersion':: d.fn(help='"API version of the referent."', args=[d.arg(name='apiVersion', type=d.T.string)]),
            withApiVersion(apiVersion): { machineHealthCheck+: { remediationTemplate+: { apiVersion: apiVersion } } },
            '#withFieldPath':: d.fn(help='"If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: \\"spec.containers{name}\\" (where \\"name\\" refers to the name of the container that triggered the event) or if no container name is specified \\"spec.containers[2]\\" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object. TODO: this design is not final and this field is subject to change in the future."', args=[d.arg(name='fieldPath', type=d.T.string)]),
            withFieldPath(fieldPath): { machineHealthCheck+: { remediationTemplate+: { fieldPath: fieldPath } } },
            '#withKind':: d.fn(help='"Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"', args=[d.arg(name='kind', type=d.T.string)]),
            withKind(kind): { machineHealthCheck+: { remediationTemplate+: { kind: kind } } },
            '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { machineHealthCheck+: { remediationTemplate+: { name: name } } },
            '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
            withNamespace(namespace): { machineHealthCheck+: { remediationTemplate+: { namespace: namespace } } },
            '#withResourceVersion':: d.fn(help='"Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
            withResourceVersion(resourceVersion): { machineHealthCheck+: { remediationTemplate+: { resourceVersion: resourceVersion } } },
            '#withUid':: d.fn(help='"UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"', args=[d.arg(name='uid', type=d.T.string)]),
            withUid(uid): { machineHealthCheck+: { remediationTemplate+: { uid: uid } } },
          },
          '#unhealthyConditions':: d.obj(help='"UnhealthyConditions contains a list of the conditions that determine whether a node is considered unhealthy. The conditions are combined in a logical OR, i.e. if any of the conditions is met, the node is unhealthy."'),
          unhealthyConditions: {
            '#withTimeout':: d.fn(help='', args=[d.arg(name='timeout', type=d.T.string)]),
            withTimeout(timeout): { timeout: timeout },
            '#withType':: d.fn(help='', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { type: type },
          },
          '#withMaxUnhealthy':: d.fn(help='"Any further remediation is only allowed if at most \\"MaxUnhealthy\\" machines selected by \\"selector\\" are not healthy."', args=[d.arg(name='maxUnhealthy', type=d.T.any)]),
          withMaxUnhealthy(maxUnhealthy): { machineHealthCheck+: { maxUnhealthy: maxUnhealthy } },
          '#withNodeStartupTimeout':: d.fn(help='"Machines older than this duration without a node will be considered to have failed and will be remediated. If you wish to disable this feature, set the value explicitly to 0."', args=[d.arg(name='nodeStartupTimeout', type=d.T.string)]),
          withNodeStartupTimeout(nodeStartupTimeout): { machineHealthCheck+: { nodeStartupTimeout: nodeStartupTimeout } },
          '#withUnhealthyConditions':: d.fn(help='"UnhealthyConditions contains a list of the conditions that determine whether a node is considered unhealthy. The conditions are combined in a logical OR, i.e. if any of the conditions is met, the node is unhealthy."', args=[d.arg(name='unhealthyConditions', type=d.T.array)]),
          withUnhealthyConditions(unhealthyConditions): { machineHealthCheck+: { unhealthyConditions: if std.isArray(v=unhealthyConditions) then unhealthyConditions else [unhealthyConditions] } },
          '#withUnhealthyConditionsMixin':: d.fn(help='"UnhealthyConditions contains a list of the conditions that determine whether a node is considered unhealthy. The conditions are combined in a logical OR, i.e. if any of the conditions is met, the node is unhealthy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='unhealthyConditions', type=d.T.array)]),
          withUnhealthyConditionsMixin(unhealthyConditions): { machineHealthCheck+: { unhealthyConditions+: if std.isArray(v=unhealthyConditions) then unhealthyConditions else [unhealthyConditions] } },
          '#withUnhealthyRange':: d.fn(help='"Any further remediation is only allowed if the number of machines selected by \\"selector\\" as not healthy is within the range of \\"UnhealthyRange\\". Takes precedence over MaxUnhealthy. Eg. \\"[3-5]\\" - This means that remediation will be allowed only when: (a) there are at least 3 unhealthy machines (and) (b) there are at most 5 unhealthy machines"', args=[d.arg(name='unhealthyRange', type=d.T.string)]),
          withUnhealthyRange(unhealthyRange): { machineHealthCheck+: { unhealthyRange: unhealthyRange } },
        },
        '#template':: d.obj(help='"Template is a local struct containing a collection of templates for creation of MachineDeployment objects representing a set of worker nodes."'),
        template: {
          '#bootstrap':: d.obj(help='"Bootstrap contains the bootstrap template reference to be used for the creation of worker Machines."'),
          bootstrap: {
            '#ref':: d.obj(help='"Ref is a required reference to a custom resource offered by a provider."'),
            ref: {
              '#withApiVersion':: d.fn(help='"API version of the referent."', args=[d.arg(name='apiVersion', type=d.T.string)]),
              withApiVersion(apiVersion): { template+: { bootstrap+: { ref+: { apiVersion: apiVersion } } } },
              '#withFieldPath':: d.fn(help='"If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: \\"spec.containers{name}\\" (where \\"name\\" refers to the name of the container that triggered the event) or if no container name is specified \\"spec.containers[2]\\" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object. TODO: this design is not final and this field is subject to change in the future."', args=[d.arg(name='fieldPath', type=d.T.string)]),
              withFieldPath(fieldPath): { template+: { bootstrap+: { ref+: { fieldPath: fieldPath } } } },
              '#withKind':: d.fn(help='"Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"', args=[d.arg(name='kind', type=d.T.string)]),
              withKind(kind): { template+: { bootstrap+: { ref+: { kind: kind } } } },
              '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { template+: { bootstrap+: { ref+: { name: name } } } },
              '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { template+: { bootstrap+: { ref+: { namespace: namespace } } } },
              '#withResourceVersion':: d.fn(help='"Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
              withResourceVersion(resourceVersion): { template+: { bootstrap+: { ref+: { resourceVersion: resourceVersion } } } },
              '#withUid':: d.fn(help='"UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"', args=[d.arg(name='uid', type=d.T.string)]),
              withUid(uid): { template+: { bootstrap+: { ref+: { uid: uid } } } },
            },
          },
          '#infrastructure':: d.obj(help='"Infrastructure contains the infrastructure template reference to be used for the creation of worker Machines."'),
          infrastructure: {
            '#ref':: d.obj(help='"Ref is a required reference to a custom resource offered by a provider."'),
            ref: {
              '#withApiVersion':: d.fn(help='"API version of the referent."', args=[d.arg(name='apiVersion', type=d.T.string)]),
              withApiVersion(apiVersion): { template+: { infrastructure+: { ref+: { apiVersion: apiVersion } } } },
              '#withFieldPath':: d.fn(help='"If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: \\"spec.containers{name}\\" (where \\"name\\" refers to the name of the container that triggered the event) or if no container name is specified \\"spec.containers[2]\\" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object. TODO: this design is not final and this field is subject to change in the future."', args=[d.arg(name='fieldPath', type=d.T.string)]),
              withFieldPath(fieldPath): { template+: { infrastructure+: { ref+: { fieldPath: fieldPath } } } },
              '#withKind':: d.fn(help='"Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"', args=[d.arg(name='kind', type=d.T.string)]),
              withKind(kind): { template+: { infrastructure+: { ref+: { kind: kind } } } },
              '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { template+: { infrastructure+: { ref+: { name: name } } } },
              '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { template+: { infrastructure+: { ref+: { namespace: namespace } } } },
              '#withResourceVersion':: d.fn(help='"Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
              withResourceVersion(resourceVersion): { template+: { infrastructure+: { ref+: { resourceVersion: resourceVersion } } } },
              '#withUid':: d.fn(help='"UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"', args=[d.arg(name='uid', type=d.T.string)]),
              withUid(uid): { template+: { infrastructure+: { ref+: { uid: uid } } } },
            },
          },
          '#metadata':: d.obj(help='"Metadata is the metadata applied to the machines of the MachineDeployment. At runtime this metadata is merged with the corresponding metadata from the topology."'),
          metadata: {
            '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
            withAnnotations(annotations): { template+: { metadata+: { annotations: annotations } } },
            '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
            withAnnotationsMixin(annotations): { template+: { metadata+: { annotations+: annotations } } },
            '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
            withLabels(labels): { template+: { metadata+: { labels: labels } } },
            '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
            withLabelsMixin(labels): { template+: { metadata+: { labels+: labels } } },
          },
        },
        '#withClass':: d.fn(help='"Class denotes a type of worker node present in the cluster, this name MUST be unique within a ClusterClass and can be referenced in the Cluster to create a managed MachineDeployment."', args=[d.arg(name='class', type=d.T.string)]),
        withClass(class): { class: class },
      },
      '#withMachineDeployments':: d.fn(help='"MachineDeployments is a list of machine deployment classes that can be used to create a set of worker nodes."', args=[d.arg(name='machineDeployments', type=d.T.array)]),
      withMachineDeployments(machineDeployments): { spec+: { workers+: { machineDeployments: if std.isArray(v=machineDeployments) then machineDeployments else [machineDeployments] } } },
      '#withMachineDeploymentsMixin':: d.fn(help='"MachineDeployments is a list of machine deployment classes that can be used to create a set of worker nodes."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='machineDeployments', type=d.T.array)]),
      withMachineDeploymentsMixin(machineDeployments): { spec+: { workers+: { machineDeployments+: if std.isArray(v=machineDeployments) then machineDeployments else [machineDeployments] } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
